Repository ArthurVillette/SAE_RESAUX, pull requests merged in 2024-01, with the labels that each got.

#1 Feat/terminal
  lib/gson-2.8.2.jar
  scriptClient.sh
  scriptCompil.sh
  scriptServeur.sh
  src/Client.java
  src/ClientEnvoie.java
  src/ClientRecept.java
  src/Commande.java
  src/GestionClient.java
  src/GestionCommande.java
  src/GestionMessage.java
  src/GestionUtilisateurs.java
  src/Message.java
  src/Serveur.java
  src/ServeurThread.java
  src/ServeurThreadEnvoie.java
  src/Utilisateur.java
Labels: enhancement

#2 Doc/readme_docstring to develop
  README.md
  src/Client.java
  src/ClientEnvoie.java
  src/ClientRecept.java
  src/Commande.java
  src/GestionClient.java
  src/GestionCommande.java
  src/GestionMessage.java
  src/GestionUtilisateurs.java
  src/Message.java
  src/Serveur.java
  src/ServeurThread.java
  src/ServeurThreadEnvoie.java
  src/Utilisateur.java
Labels: documentation

#3 Feat/bd
  bd/creation.sql
  lib/mysql-connector-java-8.0.20.jar
  scriptClient.sh
  scriptServeur.sh
  src/ClientRecept.java
  src/ConnexionMySQL.java
  src/GestionMessage.java
  src/GestionUtilisateurs.java
  src/Serveur.java
  src/ServeurThread.java
Labels: bug, enhancement

#4 doc/ to develop
  README.md
  src/GestionMessage.java
  src/GestionUtilisateurs.java
  src/Serveur.java
Labels: documentation
